---
ID: "298e3e64-1c59-42d1-b9f2-398732f3b18c"
Parent: "0ea559cc-ef81-453c-bf36-48c472039793"
Template: "0ea559cc-ef81-453c-bf36-48c472039793"
Path: /sitecore/templates/Feature/Marketing Sites/SiteA/Callout Banner/CalloutBanner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250817T155939Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a6f40174-3151-4ad3-90f0-dc03b6f767d8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250817T155939Z
