---
ID: "96f7a769-58af-4f1b-90d8-0cd11c90756d"
Parent: "eb59fce7-45aa-4645-8148-1eccaae39aae"
Template: "eb59fce7-45aa-4645-8148-1eccaae39aae"
Path: /sitecore/templates/Feature/Marketing Sites/SiteA/Feature Section/FeatureSection/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{09221D67-8977-4664-9388-1B62827EF5E0}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250819T141821Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e878e610-e64e-4c77-82cd-85ce2ee1dd63"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250819T141835Z
