---
ID: "3a4bd1a5-e1d2-4b6a-9b84-8adc22ecb22b"
Parent: "3b5bb909-86df-4ee8-a4d6-9b2f9ae8762f"
Template: "3b5bb909-86df-4ee8-a4d6-9b2f9ae8762f"
Path: /sitecore/templates/Feature/Marketing Sites/SiteA/Stats Section/StatsSection/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{08C67AC3-D476-474A-A479-4C376627DE6D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250818T090452Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "93d5999f-780d-47c9-acd5-36cda7ca7f48"
    - ID: "a61cee6d-3278-4399-987a-c8d545e6366e"
      Hint: title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250818T091030Z
